# Generated by Django 6.0.3 on 2026-05-08 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_empresa.empresamodel')),
            ],
        ),
    ]
